{% set version = "0.1.4" %}

package:
   name:  xrviz
   version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xrviz/xrviz-{{ version }}.tar.gz
  sha256: 65deb63b695f4edcfa5d4eb85319c0f48ac43e2fbc796f7b8fd3e52be2261206

build:
  number: 3
  noarch: python
  entry_points:
    - xrviz = xrviz.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jinja2
  run:
    - python >={{ python_min }}
    - xarray >=0.14.1
    - cartopy
    - panel >=0.7.0
    - holoviews
    - hvplot
    - netcdf4
    - datashader
    - metpy

test:
  imports:
    - xrviz
    - xrviz.sample_data
  commands:
    - pip check
    - xrviz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake/xrviz
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "Interactive visualisation interface for Xarrays"

extra:
  recipe-maintainers:
    - martindurant
    - rsignell-usgs
    - hdsingh
