travis:
  secure:
    BINSTAR_TOKEN: FpT+M7w/9+XTvkthsVaVB9jUSRQ5xXi1P9j9hERrC0yKV/D45leZtDd1Knm1qT8pRNNDalaw5GesP8w7mQNkNG292NGK5RL0CfqETnuMqPz8JHmaYAyP/PPY40WX/95Og6/qzud04jvT/+sYqbU1cmi98mdxFrmXO0bJri5EI9KuJksiEcIVnv4MvO9m/cToFp24N9k99bHXHJnbJxQ4EIU/+VRfDXMvN8w3BQ01LL+R68ghX40jm0yXYhPAuxAXM4VOEaBnl1EoILXe+WFI/cmh5xivqdTStvs6t87qREnAxGagVlbavHPKxdknzkONO2WrWIqcdtLBqEk5ZW5AR3HHoTzTarrYce14BgrSNL9RsisBX0lahH/q/8lC0sxQkULH/f03HdX+eCwqoow3vwwg+SjuKT3HdEBYf3kHb5mIGtVOcJM3y2u017alPk6vFq/bAr60BayDtPLu1UGMyVAfgGSqQ05LFOqGXSzsWihYrbiKP03YNiamjQtdHn20mzKhqdgn4EMXFcMTF83P7h5qPEUajBSSmrTLpODevfOfi+Kht9YPSHZPkwCW3NSKsntTPELejo1WhKMcmKG3hkiOUaTKtruRZnZSYYkjjzKsQ5Kf3h97yn1Sqh82rvnppx9ai9OgJVhMBntS36RVNs8vAoK85ELW2baDY/i4cbs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
